$(document).ready(function(){$('.b-search').on('submit',function(){if($('.b-search__input',this).val()==''){return false;}});});
function BlockFolders(){Block.apply(this,arguments);}
BlockFolders.prototype=Object.create(Block.prototype);BlockFolders.constructor=BlockFolders;BlockFolders.prototype.hideSubFolders=function(){$('.b-folders__item').each(function(){var subFolders=$('.b-folders__subfolders-list .b-folders__link, .b-folders__subfolders-list span',this);if($('.b-folders__subfolders-list .b-folders__link',this).length>8){var miniSubFolders=subFolders.slice(0,8);$('.b-folders__subfolders-list',this).html(miniSubFolders).append(' <a href="#" class="b-folders__link b-folders__show-all-subfolders">...</a>');}
$('.b-folders__show-all-subfolders',this).click(function(){$(this).parent().html(subFolders);return false;});});};BlockFolders.prototype.init=function(){this.hideSubFolders();};$(function(){window.bem['b-folders']=BlockFolders;var BlockObject=new bem['b-folders'];if(!BlockObject.wasInitialized){BlockObject.init();}});BlockFolders.prototype.hideSubFolders=function(){};
function closeSelectBlock(){$('.b-sorting__list_state_opened').removeClass('b-sorting__list_state_opened');$('.b-sorting__selected_state_opened').removeClass('b-sorting__selected_state_opened');}
$(document).ready(function(){$('.b-sorting__select').click(function(){if($(this).find('.b-sorting__list').hasClass('b-sorting__list_state_opened')){closeSelectBlock();}else{$('.b-sorting__list_state_opened').removeClass('b-sorting__list_state_opened');$('.b-sorting__selected_state_opened').removeClass('b-sorting__selected_state_opened');$(this).find('.b-sorting__selected').toggleClass('b-sorting__selected_state_opened');$(this).find('.b-sorting__list').toggleClass('b-sorting__list_state_opened').css("min-width",$(this).width()-2);}});});$(document).click(function(e){var target=$(e.target);if(!target.hasClass('b-sorting__select')&&target.parents('.b-sorting__select').length==0){closeSelectBlock();}});
function BlockProductsGallery(){}
BlockProductsGallery.prototype=Object.create(Block.prototype);BlockProductsGallery.prototype.attachDomReady=function(){var $productsGallery=$('.b-products-gallery');if($productsGallery.hasClass('b-products-gallery_mode_gallery')&&$('.b-page_theme_mobile').length==0){var productsGalleryWidth=$productsGallery.width();var $productGalleryItem=$productsGallery.find('.b-products-gallery__item');var productsGalleryItemWidth=$productGalleryItem.outerWidth(true);var countOfItemsInRow=Math.floor(productsGalleryWidth/productsGalleryItemWidth);var n=1;for(var i=0;i<$productGalleryItem.length;i+=countOfItemsInRow){$productGalleryItem.slice(i,i+countOfItemsInRow).addClass("b-products-gallery__row-"+n);$(".b-products-gallery__price",".b-products-gallery__row-"+n).equalHeights(true);$(".b-products-gallery__articul",".b-products-gallery__row-"+n).equalHeights(false);$(".b-products-gallery__name",".b-products-gallery__row-"+n).equalHeights(false);n++;}}
if($productsGallery.hasClass('b-products-gallery_size_big')&&!$('.b-page').data('theme')=='pretty'){var $availability=$(".b-availability").filter(function(){var $this=$(this);return!($this.hasClass('b-availability_status_unknown')&&$this.hasClass('b-availability_status_not-available'));});$availability.css({"line-height":$availability.height()+"px"});}
$('.b-products-gallery_columns_four .b-products-gallery__item').each(function(){if($('b-products-gallery__meta').has('.b-products-gallery__buy')&&$('.b-products-gallery__availability_status_unknown').html()){$('.b-products-gallery__availability_status_unknown').addClass("b-products-gallery__availability_status_unknown-short");}});if($.browser.msie&&parseInt($.browser.version,10)===7){$('.b-products-gallery__img').click(function(){$(window.location).attr('href',$(this).parent('a').attr('href'));});}};BlockProductsGallery.prototype.init=function(){this.attachDomReady();};$(function(){window.bem['b-products-gallery']=BlockProductsGallery;var BlockObject=new bem['b-products-gallery'];if(!BlockObject.wasInitialized){BlockObject.init();}});(function($){$.fn.equalHeights=function(margins){var currentTallest=0;this.each(function(){var $this=$(this);var currentHeight=$this.outerHeight(margins);if(currentHeight>currentTallest){currentTallest=currentHeight;}});this.css({'min-height':currentTallest,'height':currentTallest});return this;};})(jQuery);
$(document).ready(function(){if(!window.bem.bProducts){window.bem.bProducts={lastWindowWidth:window.innerWidth,sliders:[]};$(window).on('adding-new-products-slider',function(){$('.b-products_view_slider:not(.init)').each(function(i){sliderInit($(this));});});$('.b-products_view_slider:not(.init)').each(function(i){sliderInit($(this));});function sliderInit($bl){var opt=getSliderOptions($bl);$bl.bxSlider(opt);$bl.removeClass('i-ajax-indicator_big').addClass('init');var headerControls=$bl.attr('headercontrols')?true:false;if(headerControls){initHeaderControls($bl)}
window.bem.bProducts.sliders.push($bl);}
$(window).on('resize orientationchange',function(){if(window.bem.bProducts.lastWindowWidth!=window.innerWidth){window.bem.bProducts.sliders.forEach(function($bl){var opt=getSliderOptions($bl);$bl.reloadSlider(opt);});window.bem.bProducts.lastWindowWidth=window.innerWidth;}});function initHeaderControls($slider){var $widget={};if($slider.attr('mode_viewed_products')==1){$widget=$slider.parents('.b-sidebar-widget_view_viewed-products');}else{$widget=$slider.parents('.b-sidebar-widget__products-slider');}
if($slider.getSlideCount()>1){$widget.find('.b-sidebar-widget__controls-prev').on('click',function(e){e.preventDefault();$slider.goToNextSlide();});$widget.find('.b-sidebar-widget__controls-next').on('click',function(e){e.preventDefault();$slider.goToNextSlide();});}else{$widget.find('.b-sidebar-widget__controls').hide();}}
function getSliderOptions($bl){var $item=$bl.find('.b-products__item:first');var itemMinWidth=parseFloat($item.css('min-width'));if(!itemMinWidth){itemMinWidth=parseFloat($item.css('width'));$bl.find('.b-products__item').css('min-width',itemMinWidth);}
var itemMarginRight=parseFloat($item.css('margin-right'));var itemOuterWidth=Math.floor(itemMinWidth+itemMarginRight)+1;var wrapperWidth=$bl.parents('.b-sect__content, .b-sidebar-widget__content').width();var count=Math.floor((wrapperWidth+itemMarginRight)/itemOuterWidth);var itemWidth=(wrapperWidth+itemMarginRight)/count-itemMarginRight;var pager=!(count>=$bl.find('.b-products__item').length);var mode=$bl.attr('data-mode')?$bl.attr('data-mode'):'horizontal';var pause=$bl.attr('data-autoplay')?$bl.attr('data-autoplay'):0;var auto=pause>0;return{pager:pager,mode:mode,nextText:'',prevText:'',slideWidth:itemWidth,slideMargin:itemMarginRight,minSlides:1,maxSlides:10,infiniteLoop:auto,hideControlOnEnd:!auto,auto:auto,pause:pause,onSlideAfter:function(){$(window).trigger('lazyrestart');}}}}});
(function($){$(function(){if($('.b-sex-product-warning').length>0){$(this).sexproduct();}});})(jQuery);
$(function(){$('.b-search__input').each(function(){var $this=$(this);if($.fn.autocomplete){$this.autocomplete({delay:500,source:"/ajax/AutoComplete/FirmMain/?idcompany="+$this.data('idcompany'),position:{my:"left top",at:"left bottom",collision:"fit none"},select:function(event,ui){$this.val(ui.item.value);window.location=ui.item.url;}}).autocomplete("instance")._renderItem=function(ul,item){if(item.label.length>80){return $("<li title='"+item.label+"' class='cat_prod_long'>").append("<div class='img_middle'><img class='img_title' src="+item.pic_name+" /></div>"+"<p  class='cat_title_long'><a href='"+item.url+"'>"+item.label+"</a></p>"+"<p class='prod_price'>"+(item.price!=null?item.price:"&nbsp;")+"</p>").appendTo(ul);}else{return $("<li class='cat_prod_img'>").append("<div class='img_middle'><img class='img_title' src="+item.pic_name+" /></div>"+"<p class='cat_title'><a href='"+item.url+"'>"+item.label+"</a></p>"+"<p class='prod_price'>"+(item.price!=null?item.price:"&nbsp;")+"</p>").appendTo(ul);}}}});$(".b-search__submit").submit(function(){var val=$(this).parents('form').find('.b-search__input').val();if($.trim(val).length==0){return false;}});});
$(document).ready(function(){$(".i-flex-grid").each(function(){var cls=(this.firstChild&&this.firstChild.className)?this.firstChild.className:'';var e='<div class="'+cls+'"></div>';$(this).append(e+e+e+e+e+e+e);});});
$(function(){var isTouchEventsEnabled=$('html').hasClass('touchevents');var isNonMobileTheme=['standart','gnarled','adaptive','hatless','minimalism','antiqua'].indexOf($('html').data('theme'))+1;var isDesctopOnMobileView=function(){if($(window).width()<1024&&isTouchEventsEnabled&&isNonMobileTheme){return true;}
return false;};var bound=isDesctopOnMobileView()?1920:400;var ZKLazyLoad=function(){var top=$(window).height()+$(window).scrollTop();var left=$(window).width()+$(window).scrollLeft();$(".b-img_lazyload_yes:visible").each(function(){CheckLazyLoad($(this),top,left);});};var ShowImage=function(img){img.fadeOut(0);img.attr('src',img.attr('data-original-src')).removeClass('b-img_lazyload_yes').removeAttr('data-original-src');img.fadeIn(500);}
var CheckLazyLoad=function(img,top,left){if((img.offset().top<top+bound&&img.offset().left<left+bound)){ShowImage(img);}};ZKLazyLoad();$(window).on('scroll touchmove resize orientationchange lazyrestart',function(){ZKLazyLoad();});$(document).on('click','.bx-next, .bx-prev',function(){setTimeout(ZKLazyLoad,200);});});
$(function(){$(document).on("click",".b-folders-new__more a",function(){var $this=$(this),$more=$(this).closest('.b-folders-new__more'),all=$more.data('all'),id=$more.data('id'),limit=$more.data('limit'),$list=$more.closest('.b-folders-new'),exist=[];$list.children('.b-folders-new__item').each(function(){exist.push($(this).data('folder'));});$.ajax({url:'/data/get-more-home-goods-groups/',type:'POST',dataType:'HTML',data:{id:id,exist:exist.join(',')},success:function(data){console.log();var $lastItem=$('.b-folders-new__item:not(:empty)',$list).last();$lastItem.after(data);var count=$list.children('.b-folders-new__item').length;if(count>=all){$more.hide();}else if(all-count<limit){$this.children('.b-link-title').text(all-count);}}});return false;});});
$(document).ready(function(){$(function(){$(".firm-folders-switcher").click(function(){if($(this).attr("all")){$(this).parents("ul").children("li:gt(19)").hide();$(this).html("Показать все").removeAttr("all");$(this).parent().show();}else{$(this).parents("ul").children("li").show();$(this).html("Скрыть").attr("all","all");}
return false;})});});
$(function(){$(document).on("click",".b-folders__more a",function(){var $this=$(this),$more=$(this).closest('.b-folders__more'),all=$more.data('all'),id=$more.data('id'),limit=$more.data('limit'),$list=$more.closest('.b-folders__list').length?$more.closest('.b-folders__list'):$more.closest('.b-folders'),exist=[];$list.children('li').each(function(){exist.push($(this).data('folder'));});$.ajax({url:'/data/get-more-home-goods-groups/',type:'POST',dataType:'HTML',data:{id:id,exist:exist.join(',')},success:function(data){$more.before(data);var count=$list.children('li').length;if(count>=all){$more.hide();}else if(all-count<limit){$this.children('.b-link-title').text(all-count);}}});return false;});});
$(document).ready(function(){if(!window.bem)window.bem={};if(!window.bem.iDropdown){window.bem.iDropdown=true;$(window).bind('click',function(){$('.i-dropdown').removeClass('i-dropdown_opened');$('.i-dropdown__button').removeClass('i-dropdown__button_menu-opened');});$("body").delegate('.i-dropdown__button','click',function(e){e.preventDefault();if(!$('.i-dropdown',this.parentNode).hasClass('i-dropdown_opened')){var parent=this.parentNode;setTimeout(function(){$('.i-dropdown',parent).addClass('i-dropdown_opened');$('.i-dropdown__button',parent).addClass('i-dropdown__button_menu-opened');fixDropdown();},10);}});var fixDropdown=function(){var $dropdown=$('.i-dropdown');$dropdown.each(function(){var $this=$(this);var offsets=$this.offset();var i=((offsets.left+$this.outerWidth())-($(window).outerWidth()));if(i>0){$this.css('margin-left','-'+(i+10)+'px');}
verticalCorrection($this);});};var verticalCorrection=function($this){$this.removeAttr('style');var $formInModal=$this.closest('.b-modal .b-form');var $mainParent=$formInModal.length?$formInModal:$('body');var maxBottomPosition=$mainParent.offset().top+$mainParent[0].offsetHeight;var dropDownBottomPosition=$this.offset().top+$this[0].offsetHeight;if(dropDownBottomPosition>maxBottomPosition){var dropDownMaxHeight=maxBottomPosition-$this.offset().top;$this.css('max-height',dropDownMaxHeight);}};}});
$(function(){if(!window.bem['b-add-to-waitlist']){window.bem['b-add-to-waitlist']=true;$(".b-add-to-waitlist").live('click',function(){var $this=$(this);if($this.hasClass('b-add-to-waitlist_state_added')){return true;}
if($this.is('[data-islogged]')){$.ajax({url:"/ajax/Waitlist/AddProduct/",type:"post",data:({variant_id:$this.data("variant-id")}),success:function(data){$(document).cabinetReport(data);if(data.type=='success'){$this.addClass('b-add-to-waitlist_added').html('<a href="http://'+$this.data("siteUrl")+'/cabinet_c/waitlist/" target="_blank">Вы подписаны на этот товар</a>');$(document).trigger("waitlist:added",$this.data("variant-id"));}}});}else{$.ajax({url:"/ajax/Waitlist/GetForm/html",type:"post",data:({variant_id:$this.data("variant-id"),lang:$('.b-page').attr('lang'),env:'minisite'}),dataType:"html",success:function(data){$('body').append(data);$('.b-waitlist-dialog').zkModal();}});}
return false;});}});
if(!window.bem.bContactFirm){window.bem.bContactFirm=true;var ajaxWait=0;$(".b-contact-firm").live('click',function(){var $this=$(this);if($this.attr('href')!==undefined&&$(this).attr('href')!='#'){return true;}
if(!ajaxWait){ajaxWait=1;$.ajax({type:"POST",url:'/data/contact-form/',data:{idcompany:$this.data('name'),ref:$(this).attr("data-alt"),type:$(this).attr("data-type")=='product'?'product':'firm'},success:function(response){ajaxWait=0;$('body').append(response);$('.b-contact-dialog').zkModal();}});}});}
var zoomedWasInitialized=false;function movePopup(el){var img=$('img',el);var w=img.data('width');var h=img.data('height');var ww=$(window).width();var wh=$(window).height();var ratio=w/h;var wratio=ww/wh;if(ratio>wratio&&w+80>ww){w=ww-80;h=Math.round(w/ratio);}
if(ratio<wratio&&h+80>wh){h=wh-80;w=Math.round(h*ratio);}
$(el).css({top:((wh-h-40)/2),left:(ww-w-40)/2,'zIndex':10001});img.css('width',w);}
function drawPopUp(el){$("#zoomed-mask").show();var container=$(el).parents('.b-img__zoomed-container');container.show();movePopup(container);}
function randomString(length){var result='';var chars='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-';for(var i=length;i>0;--i)result+=chars[Math.round(Math.random()*(chars.length-1))];return result;}
function zoomIt(){console.log("zoomIt()");var iid=$(this).data('id');if($('#zoomed-'+iid).length==0){var image=$(this).attr('src').replace(/pic_/,'').replace(/_([0-9])\d+x([0-9])\d+_\d/g,'').replace('/i/','/files/');$(document.body).append($('<div class="b-img__zoomed-container" style="position:fixed;padding:20px;background: #CACACA; border:3px solid #CACACA; border-radius: 10px;"><a href="'+image+'" target="_blank" class="b-img__zoomed-source-link"><img src="'+image+'"  id="zoomed-'+iid+'" /></a><a href="#" class="b-img__zoomed-close" title="Закрыть"></a></div>'));$('#zoomed-'+iid).get(0).onload=function(){$(this).data('width',$(this).width());$(this).data('height',$(this).height());drawPopUp($(this));}}else{drawPopUp($('#zoomed-'+iid));}}
function attachZoom(){$('.b-img_func_zoomed:not([data-passed="1"])').each(function(){$(this).on('click',zoomIt);$(this).attr('data-passed',1);var id='';while(1){id=randomString(16);if($('#zoomed-'+id).length==0){$(this).attr('data-id',id);break;}}});}
$(function(){if(!zoomedWasInitialized){attachZoom();function resizeMask(){var ww=$(window).width();var wh=$(window).height();$("#zoomed-mask").css({width:ww,height:wh});if($('.b-img__zoomed-container:visible').length>0){movePopup($('.b-img__zoomed-container:visible').eq(0));}}
if($("#zoomed-mask").length==0){$(document.body).append("<div id='zoomed-mask' style='z-index:10000;position:fixed;display:none;top:0;right:0;background:#000000;opacity:0.6'></div>");$(window).resize(resizeMask);$("#zoomed-mask").click(function(){$('.b-img__zoomed-container').hide();$(this).hide();});resizeMask();}
$(document).on('click','.b-img__zoomed-close',function(){$('.b-img__zoomed-container').hide();$("#zoomed-mask").hide();return false;});$(document).on('click','.b-img__zoomed-source-link',function(){var img=$('img',this);return(img.width()<img.data('width'));});$(document).on('variant-description-render',function(){attachZoom();});zoomedWasInitialized=true;}});
$(function(){var isTouchEventsEnabled=$('html').hasClass('touchevents');var isNonMobileTheme=['standart','gnarled','adaptive','hatless','minimalism','antiqua'].indexOf($('html').data('theme'))+1;var isDesctopOnMobileView=function(){if($(window).width()<1024&&isTouchEventsEnabled&&isNonMobileTheme){return true;}
return false;};var bound=isDesctopOnMobileView()?1920:400;var ZKLazyLoad=function(){var top=$(window).height()+$(window).scrollTop();var left=$(window).width()+$(window).scrollLeft();$(".b-img_lazyload_yes:visible").each(function(){CheckLazyLoad($(this),top,left);});};var ShowImage=function(img){img.fadeOut(0);img.attr('src',img.attr('data-original-src')).removeClass('b-img_lazyload_yes').removeAttr('data-original-src');img.fadeIn(500);}
var CheckLazyLoad=function(img,top,left){if((img.offset().top<top+bound&&img.offset().left<left+bound)){ShowImage(img);}};ZKLazyLoad();$(window).on('scroll touchmove resize orientationchange lazyrestart',function(){ZKLazyLoad();});$(document).on('click','.bx-next, .bx-prev',function(){setTimeout(ZKLazyLoad,200);});});