(function($){$(function(){if($(".b-contacts-page-branches__offices li").length>10){$(".b-contacts-page-branches__offices").hide();}
$(".b-contacts-page-branches__office-name").click(function(){var $this=$(this);var $icon=$this.parent().find(".b-font-icon__location");var $offices=$this.closest('.b-contacts-page-branches__area-row').find('.b-contacts-page-branches__offices');$icon.toggleClass("b-font-icon_color_grey");$this.toggleClass("b-contacts-page-branches__toggled");$offices.toggle();return false;});});})(jQuery);
$(document).ready(function(){$('.b-phone__show-all:not(.clickHandlerInit)').on('click',function(){$(this).parent().toggleClass('opened-all');});window.bem.bPhones={initPhones:function(){var $dropDowns=$('.b-phone__all_view_dropdown:not(.init)');$dropDowns.each(function(){var $dd=$(this);var $button=$dd.prev();$('body').append($dd.addClass('init'));$button.on('click',function(){var $el=$(this).parent();var left=Math.round($el.offset().left);var top=Math.round($el.offset().top+$el[0].offsetHeight);if(!$dd.hasClass('opened')){setTimeout(function(){$dd.css({'left':left,'top':top}).addClass('opened');$el.addClass('b-phone__numbers_dd_opened');normalizePosition($dd);},20);}
else{$dd.removeClass('opened');$('.b-phone__numbers_dd_opened').removeClass('b-phone__numbers_dd_opened');}});});}}
window.bem.bPhones.initPhones();$('.b-phone__show-all, .b-phone__show-dropdown').addClass('clickHandlerInit');$(window).on('click resize',function(e){if(!$(e.target).hasClass('b-phone__show-all')){$('.b-phone__numbers').removeClass('opened-all');}
if(!$(e.target).hasClass('b-phone__show-dropdown')){$('.b-phone__all_view_dropdown.init').removeClass('opened');$('.b-phone__numbers_dd_opened').removeClass('b-phone__numbers_dd_opened');}});function getRelationPosition($elem){var $win=$(window);return{'left':$elem.offset().left-$win.scrollLeft(),'top':$elem.offset().top-$win.scrollTop(),'right':$win.scrollLeft()+$win.innerWidth()-$elem.offset().left-$elem.outerWidth(),'bottom':$win.scrollTop()+$win.innerHeight()-$elem.offset().top-$elem.outerHeight(),}}
function normalizePosition($elem){var pos=getRelationPosition($elem);if(pos.bottom<0){if(pos.bottom+pos.top>=0){$elem.css('top',parseInt($elem.css('top'))+pos.bottom);}
else{$elem.css('top',parseInt($elem.css('top'))-pos.top);}}
if(pos.left<0){if(pos.left+pos.right>=0){$elem.css('left',parseInt($elem.css('left'))-pos.left);}}
if(pos.right<0){if(pos.left+pos.right>=0){$elem.css('left',parseInt($elem.css('left'))+pos.right);}}}});
$(function(){if(!window.bem.bFirmOnMap){window.bem.bFirmOnMap=true;$('.b-firm-on-map').click(function(){var $this=$(this);var geo=$this.data('geo');var address=$this.data('address');var phones=$this.data('phones');var src=$this.data('siteurl')+'/map-address/'+$this.data('idcompany')+'/';var dataSrc=src;if($this.data('editor-map-url'))src=$this.data('editor-map-url');var $params=[];if(typeof geo!=='undefined')$params.push('geo='+geo);if(typeof address!=='undefined')$params.push('address='+address);if(typeof phones!=='undefined')$params.push('phones='+phones);src+='?'+$params.join('&');$('body').append('<iframe data-title="'+$this.data('dialog-title')+'" class="b-firm-on-map__dialog" data-src="'+dataSrc+'/" frameborder="0" border="0" scrolling="no" src="'+src+'"></iframe>');$('.b-firm-on-map__dialog').zkModal({withoutPadding:true,maxAutoHeight:550});return false;});}});
$(document).ready(function(){$('.b-list').each(function(){if($(this).hasClass('b-list_visibility_hide')){$(this).prev().click(function(){$(this).removeClass('b-list__show-all_arrow_down');$(this).next().removeClass('b-list_visibility_hide');$(this,'.b-contacts__show-all-text').hide();});}});});
var first_exec=first_exec||true;(function($){"use strict";$(function(){if(!first_exec)return;first_exec=false;$('.b-hidden-phone').hiddenPhone();$(document).on('click','.b-contacts-all__show-all',function(e){e.preventDefault();var $this=$(this);var $phonesTable=$this.parent().find('.b-contacts__telephones-table');fixAlignmentOfListPhones($phonesTable,$this);var overlay=$('<div />',{'class':'b-contacts__telephones-table-overlay'});if(!$(document).find('.b-contacts__telephones-table-overlay').length){overlay.appendTo($this.parent());overlay.addClass('show');}
$(document).on('click','.b-contacts__telephones-table-overlay',function(e){e.preventDefault();$phonesTable.removeClass('open').hide(0);overlay.removeClass('show');});if($phonesTable.hasClass('open')){$phonesTable.removeClass('open').hide(0);}else{$phonesTable.addClass('open').show(0);}});});$.fn.hiddenPhone=function(){$.each(this,function(){var self=$(this);var hiddenPhoneElement=self.find('.b-hidden-phone__begin');var $hiddenPhonesList="";var hasPhoneList=false;showCattedPhoneInElement(hiddenPhoneElement);addGaEvents();if(self.parent().find('.b-contacts__telephones-table').size()){$hiddenPhonesList=self.parent().find('.b-contacts__telephones-table');hasPhoneList=true;fixAlignmentOfListPhones($hiddenPhonesList,hiddenPhoneElement);}
self.on('click',function(){var $this=$(this);if(!$this.hasClass('opened')){hiddenPhone($this,'show');if(hasPhoneList){$hiddenPhonesList.show();setTimeout(function(){$(document).on('click.hiddenphone',function(e){var target=$(e.target);$('.b-contacts__telephones-table').on('click.hiddenphone',function(e){e.stopPropagation();});if(!target.hasClass('b-contacts__telephones-table')){hiddenPhone($this,'hide');$hiddenPhonesList.hide();$(document,'.b-contacts__telephones-table').off('click.hiddenphone');}});},10);}}else{hiddenPhone($this,'hide');if(hasPhoneList){$hiddenPhonesList.hide();}}});});};var hiddenPhone=function(element,action){var $this=element;var $showButton=$this.find('.b-hidden-phone__show');var $hiddenPhone=$this.find('.b-hidden-phone__begin');switch(action){case'show':$showButton.hide();showOriginPhone($hiddenPhone);$this.addClass('opened');break;case'hide':$showButton.show();hideOriginPhoneShowCut($hiddenPhone);$this.removeClass('opened');break;}};var addGaEvents=function(){$.each($('.b-stats-tracking__phone'),function(){var self=$(this);if(!self.hasClass('ready')){self.addClass('ready').on('click',function(){var category=$(this).data('category');var action=$(this).data('action');var label=$(this).data('label');var ua=$(this).data('ua');if(ua!=undefined){ga('create',ua,'auto','b_hidden_phone');ga('b_hidden_phone.send','event',category,action,label);}
ga('create',$(this).data('siteua'),'auto',{'name':'siteTracker_b_hidden_phone'});ga('siteTracker_b_hidden_phone.send','event',category,action,label);$(this).addClass('clicked');});}});};var cattedPhone=function(phone){var cattedPhoneString="";var phoneLength=phone.length;var j=0;for(var i=0;i<phoneLength;i++){if(typeof(phone[i])=="undefined"){continue;}
cattedPhoneString+='<span style="opacity: 0.'+(8-j)+'">'+phone[i]+'</span>';j+=(phone[i]!=' '&&phone[i]!='('&&phone[i]!=')')?1:0;if(j==8)break;}
return cattedPhoneString;};var showCattedPhoneInElement=function(element){var phone=element.text();element.attr('data-origin-phone',phone);element.html(cattedPhone(phone));element.show();};var showOriginPhone=function(element){var originPhone=element.attr('data-origin-phone');element.html(originPhone);element.addClass('dashed unhidden');};var hideOriginPhoneShowCut=function(element){var phone=element.data('origin-phone');element.removeClass('dashed unhidden');element.html(cattedPhone(phone));};var fixAlignmentOfListPhones=function($elementPhonesList,$buttonBlock){var $wrapper=$('.b-wrapper');var $container=$wrapper.size()?$wrapper:$('.b-container');var containerOffset=$container.length>0?($container.outerWidth()+$container.offset().left):0;var phonesListWidth=$elementPhonesList.outerWidth();var $buttonBlockOffset=$buttonBlock.length>0?$buttonBlock.offset().left:0;if((phonesListWidth+$buttonBlockOffset)>containerOffset){$elementPhonesList.css({right:0});}};})(jQuery);
$(document).ready(function(){$('.i-js-spoiler').each(function(){var $this=$(this);var fz=parseInt($this.css('font-size'));if($this.height()>fz*5){$this.addClass('hidden');$this.append('<span class="i-js-spoiler__link">показать</span>');}});$('.i-js-spoiler__link').click(function(){$(this).parent().removeClass('hidden');});});
$(document).ready(function(){window.bem.bPhones.initHiddenPhones=function(){$('.b-phone__hidden-begin:not(.init)').each(function(){$this=$(this);$this.html(cattedPhone($this.text()));$this.addClass('init').css('display','inline');});addGaEvents();};window.bem.bPhones.initHiddenPhones();function cattedPhone(phone){var cattedPhoneString="";var phoneLength=phone.length;var j=0;for(var i=0;i<phoneLength;i++){if(typeof(phone[i])=="undefined"){continue;}
cattedPhoneString+='<span style="opacity: 0.'+(8-j)+'">'+phone[i]+'</span>';j+=(phone[i]!=' '&&phone[i]!='('&&phone[i]!=')')?1:0;if(j==8)break;}
return cattedPhoneString;}
function addGaEvents(){$.each($('.b-stats-tracking__phone'),function(){var $this=$(this);if(!$this.hasClass('ready')){$this.addClass('ready').on('click',function(){var category=$this.data('category');var action=$this.data('action');var label=$this.data('label');var ua=$this.data('ua');if(ua!=undefined){ga('create',ua,'auto','b_hidden_phone');ga('b_hidden_phone.send','event',category,action,label);}
ga('create',$this.data('siteua'),'auto',{'name':'siteTracker_b_hidden_phone'});ga('siteTracker_b_hidden_phone.send','event',category,action,label);$this.addClass('clicked');});}});}});